Algoritmo "Repetição_Para_Ate"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)Neliane de Oliveira
// Data atual  : 24/05/2022
Var
// Seção de Declarações das variáveis 
C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  Para C<- 1 ate 10 passo 1 faça
  escreval(C)
  fimpara

Fimalgoritmo