Algoritmo "Valores_Relacionais"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a) Neliane de Oliveira
// Data atual  : 17/05/2022
Var
// Seção de Declarações das variáveis 

   a,b,c: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  a<-2
  b<-3
  C<-5
  escreva(nao((a=b) e (c>a)))

Fimalgoritmo